# Generated by Django 3.0.6 on 2020-05-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_content', models.TextField()),
                ('news_published', models.DateTimeField(verbose_name='data published')),
            ],
        ),
    ]
