# Generated by Django 3.0.6 on 2020-05-23 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 15, 24, 35, 497451), verbose_name='data published'),
        ),
    ]
